source 'https://rubygems.org'
gemspec

os_path = ENV.fetch('VPSADMINOS_PATH') do
  abort 'VPSADMINOS_PATH is not set; run `nix develop .#nodectld` or set it ' \
        'to a vpsAdminOS checkout'
end

unless File.directory?(os_path)
  abort "VPSADMINOS_PATH does not exist: #{os_path}"
end

gem 'libnodectld', path: '../libnodectld'
gem 'libosctl', path: File.join(os_path, 'libosctl')
gem 'osctl', path: File.join(os_path, 'osctl')
gem 'osctl-exportfs', path: File.join(os_path, 'osctl-exportfs')

group :development do
  gem 'rake'
end
