require_relative '../tools/vpsadminos'

begin
  Vpsadminos.export_build_id_env!
rescue Vpsadminos::Error => e
  abort e.message
end

source 'https://rubygems.org'
gemspec

if ENV.has_key?('VPSADMIN_BUILD_ID')
  source 'https://rubygems.vpsfree.cz' do
    gem 'libnodectld'
    gem 'libosctl'
    gem 'osctl'
    gem 'osctl-exportfs'
  end
else
  gem 'libnodectld', path: '../libnodectld'

  if Vpsadminos.local_checkout?
    os_path = Vpsadminos.source_path

    gem 'libosctl', path: File.join(os_path, 'libosctl')
    gem 'osctl', path: File.join(os_path, 'osctl')
    gem 'osctl-exportfs', path: File.join(os_path, 'osctl-exportfs')
  else
    source 'https://rubygems.vpsfree.cz' do
      gem 'libosctl'
      gem 'osctl'
      gem 'osctl-exportfs'
    end
  end
end

group :development do
  gem 'rake'
end
