PreCommit:
  Nixfmt:
    enabled: true
  RuboCop:
    enabled: true
  VpsadminApiI18n:
    enabled: true
  VpsadminWebuiI18n:
    enabled: true
  PhpCsFixer:
    enabled: true
    command: 'php-cs-fixer'
CommitMsg:
  CapitalizedSubject:
    enabled: false
