Layout/LineLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/ClassVars:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
