source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.6'
gem 'eventmachine', '1.2.7'
gem 'thin', '~> 1.6.4'

# vpsadmind deps
gem 'daemons'
gem 'json'
gem 'require_all', '~> 1.5.0'
gem 'pry-remote'
gem 'mail'
gem 'mysql'
