source 'https://rubygems.org'

gem 'activerecord', '~> 7.0.4'
gem 'eventmachine', '1.2.7'
gem 'mysql2', '~> 0.5.3'
gem 'require_all', '~> 2.0.0'
gem 'sinatra', '~> 3.0.6'
gem 'sinatra-activerecord', '~> 2.0.23'
gem 'thin'
