# List of custom routes covered by request specs
covered_custom_routes:
- "GET /metrics"
- "GET /oauth2/password-reset"
- "GET /oauth2/password-reset/complete"
- "GET /oauth2/password-reset/continue"
- "GET /oauth2/password-reset/password"
- "GET /oauth2/password-reset/sent"
- "GET /oauth2/password-reset/verify"
- "GET /sd/download-pools"
- "GET /webauthn/registration/new"
- "POST /oauth2/password-reset"
- "POST /oauth2/password-reset/continue"
- "POST /oauth2/password-reset/password"
- "POST /oauth2/password-reset/verify/totp"
- "POST /oauth2/password-reset/verify/webauthn/begin"
- "POST /oauth2/password-reset/verify/webauthn/finish"
