source 'https://rubygems.org'
gemspec

if ENV.has_key?('VPSADMIN_BUILD_ID')
  source 'https://rubygems.vpsfree.cz' do
    gem 'libnodectld'
    gem 'libosctl'
    gem 'osctl'
    gem 'osctl-exportfs'
  end
else
  os_path = ENV['OS'] || '../../vpsadminos'

  gem 'libnodectld', path: '../libnodectld-v5'
  gem 'libosctl', path: File.join(os_path, 'libosctl')
  gem 'osctl', path: File.join(os_path, 'osctl')
  gem 'osctl-exportfs', path: File.join(os_path, 'osctl-exportfs')
end

group :development do
  gem 'rake'
end
