source 'https://rubygems.vpsfree.cz/'
gemspec

if !ENV.has_key?('VPSADMIN_BUILD_ID')
  os_path = ENV['OS'] || '../../vpsadminos'

  gem 'libosctl', path: File.join(os_path, 'libosctl')
  gem 'osctl', path: File.join(os_path, 'osctl')
  gem 'osctl-exportfs', path: File.join(os_path, 'osctl-exportfs')
  gem 'libnodectld', path: '../libnodectld'
end
