source 'https://rubygems.vpsfree.cz/'
gemspec

os_path = ENV['OS'] || '../../vpsadminos'

gem 'libosctl', path: File.join(os_path, 'libosctl')
gem 'osctl', path: File.join(os_path, 'osctl')
gem 'libnodectld', path: '../libnodectld'
