#! /bin/sh
### BEGIN INIT INFO
# Provides:          vpsadmin
# Required-Start:    $syslog $time $networking $vz
# Required-Stop:     $syslog $time $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenVZ web control panel daemon
# Description:       OpenVZ web control panel daemon

### END INIT INFO
#
# Author:	Pavel Snajdr <snajpa@snajpa.net>, Tomas Srnka <tomas.srnka@gmail.com>
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/php
DAEMONFILE="/opt/vpsadmin/daemon.php > /dev/null 2>&1"
PIDFILE=/var/run/vpsadmin.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting vpsAdmin's daemon" "vpsadmin"
	start_daemon -p $PIDFILE "$DAEMON $DAEMONFILE"
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping vpsAdmin's daemon" "vpsadmin"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON vpsadmin && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/vpsadmin {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
