require 'pathname'

source 'https://rubygems.org'

begin
  $: << File.realpath(File.join(__dir__, 'lib'))
rescue Errno::ENOENT
  # ignore
end

gem 'activerecord', '~> 8.1.1'
gem 'ancestry', '~> 4.3.3'
gem 'base64'
gem 'bcrypt', '~> 3.1.20'
gem 'bunny', '~> 2.24.0'
gem 'dnsruby', '~> 1.73'
gem 'haveapi', '~> 0.26.0'
gem 'ipaddress', '~> 0.8.3'
gem 'mysql2', '~> 0.5.6'
gem 'paper_trail', '~> 17.0.0'
gem 'prometheus-client', '~> 4.2.3'
gem 'puma'
gem 'rake'
gem 'require_all', '~> 2.0.0'
gem 'rotp', '~> 6.3.0'
gem 'rubyzip', '~> 3.2.2' # needed by vpsFree.cz's incident reports
gem 'sinatra-activerecord', '~> 2.0.27'
gem 'user_agent_parser', '~> 2.20'
gem 'webauthn', '~> 3.4'

group :test do
  gem 'rack-test'
  gem 'rspec'
end

group :development do
  gem 'pry'
  gem 'rackup'
  gem 'rubocop'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'webrick'
  gem 'yard'
end

### vpsAdmin plugin marker ###
# Do not remove the comment above. It is used to create a Nix package with
# resolved plugin dependencies.
def vpsadmin_plugin_dir
  env = ENV['VPSADMIN_PLUGIN_DIR'].to_s.strip
  unless env.empty?
    path = env
    path = File.expand_path(path, __dir__) unless Pathname.new(path).absolute?
    return File.realpath(path) if Dir.exist?(path)
  end

  candidates = [
    File.join(__dir__, 'plugins'),
    File.expand_path('../plugins', __dir__)
  ]

  candidates.each do |candidate|
    return File.realpath(candidate) if Dir.exist?(candidate)
  end

  nil
end

def vpsadmin_allowed_plugins
  mode = ENV['VPSADMIN_PLUGINS'].to_s.strip.downcase
  return :none if mode == 'none'
  return nil if mode.empty? || mode == 'all'

  mode.split(',').map(&:strip).reject(&:empty?)
end

allowed_plugins = vpsadmin_allowed_plugins
plugin_dir = vpsadmin_plugin_dir

if allowed_plugins != :none && plugin_dir
  Dir.entries(plugin_dir).select do |v|
    v != '.' && v != '..' && File.directory?(File.join(plugin_dir, v))
  end.each do |plugin|
    next if allowed_plugins && !allowed_plugins.include?(plugin)

    path = File.join(plugin_dir, plugin, 'api', 'Gemfile')
    next unless File.exist?(path)

    eval_gemfile path
  end
end
