source 'https://rubygems.org'

begin
  $: << File.realpath(File.join(File.dirname(__FILE__), 'lib'))
rescue Errno::ENOENT
end

gem 'haveapi', '~> 0.14.0'
gem 'activerecord', '~> 6.1.4'
gem 'sinatra-activerecord', '~> 2.0.23'
gem 'paper_trail', '~> 12.1.0'
gem 'require_all', '~> 2.0.0'
gem 'rake'
gem 'composite_primary_keys', '~> 13.0.1'
gem 'eventmachine'
gem 'ancestry', '~> 4.1.0'
gem 'mysql2', '~> 0.5.3'
gem 'bcrypt', '~> 3.1.10'
gem 'ipaddress', '~> 0.8.0'
gem 'rotp', '~> 6.2.0'
gem 'thin'

group :test do
  gem 'rspec'
end

group :development do
  gem 'pry'
  gem 'yard'
end

### vpsAdmin plugin marker ###
# Do not remove the comment above. It is used to create a Nix package with
# resolved plugin dependencies.
Dir.glob(File.expand_path("../plugins/*", File.realpath(__FILE__))) do |v|
  path = File.join(v, 'api', 'Gemfile')
  next unless File.exists?(path)

  eval_gemfile path
end
