source 'https://rubygems.org'

begin
  $: << File.realpath(File.join(__dir__, 'lib'))
rescue Errno::ENOENT
  # ignore
end

gem 'activerecord', '~> 8.1.1'
gem 'ancestry', '~> 4.3.3'
gem 'base64'
gem 'bcrypt', '~> 3.1.20'
gem 'bunny', '~> 2.24.0'
gem 'dnsruby', '~> 1.73'
gem 'haveapi', '~> 0.26.0'
gem 'ipaddress', '~> 0.8.3'
gem 'mysql2', '~> 0.5.6'
gem 'paper_trail', '~> 17.0.0'
gem 'prometheus-client', '~> 4.2.3'
gem 'puma'
gem 'rake'
gem 'require_all', '~> 2.0.0'
gem 'rotp', '~> 6.3.0'
gem 'rubyzip', '~> 3.2.2' # needed by vpsFree.cz's incident reports
gem 'sinatra-activerecord', '~> 2.0.27'
gem 'user_agent_parser', '~> 2.20'
gem 'webauthn', '~> 3.4'

group :test do
  gem 'rspec'
end

group :development do
  gem 'pry'
  gem 'rackup'
  gem 'rubocop'
  gem 'rubocop-rake'
  gem 'webrick'
  gem 'yard'
end

### vpsAdmin plugin marker ###
# Do not remove the comment above. It is used to create a Nix package with
# resolved plugin dependencies.
Dir.glob(File.expand_path('../plugins/*', File.realpath(__FILE__))) do |v|
  path = File.join(v, 'api', 'Gemfile')
  next unless File.exist?(path)

  eval_gemfile path
end
