require 'bundler/setup'

if ARGV.any? { |task| task.start_with?('vpsadmin:i18n') }
  $: << File.expand_path('lib', __dir__)
  load File.expand_path('lib/vpsadmin/api/tasks/i18n.rake', __dir__)
else
  require 'active_record'
  require 'sinatra/activerecord/rake'
  require 'yard'
  require './lib/vpsadmin'
  require './lib/vpsadmin/api/tasks'
  require 'haveapi/tasks/yard'

  VpsAdmin::API::Plugin::Loader.load('api')

  YARD::Rake::YardocTask.new do |t|
    t.files   = ['lib/**/*.rb', 'models/**/*.rb']
    t.options = ['--protected', '--markup=markdown', '--output-dir=html_doc', '--files=doc/*.md']
    t.before = proc do
      document_hooks.call
      File.write(
        File.join('doc', 'Notification_templates.md'),
        ERB.new(File.read(File.join('doc', 'notification_templates.erb'))).result(binding)
      )
    end
  end

  task :log do
    ActiveRecord::Base.logger = Logger.new($stdout)
  end
end
