name: Daily update
on:
  schedule:
    - cron: '20 6 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Set up Ruby + Bundler cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update gem dependencies
        run: |
          nix develop .#vpsadmin --command bash -lc '
            ./tools/bundix_all.sh
            nixfmt packages/*/gemset.nix
          '

          git add packages
          git diff --cached --quiet && exit 0

          git commit -m "packages: update gem dependencies"

      - name: Update webui dependencies
        run: |
          cd webui

          nix develop ..#webui --command bash -lc '
            composer update
            [ -d vendor ] && rm -rf vendor
            composer2nix --name vpsadmin-webui
            nixfmt composer-env.nix php-packages.nix
          '

          git add composer.lock composer-env.nix php-packages.nix
          git diff --cached --quiet && exit 0

          git commit -m "webui: update dependencies"

      - name: Push updates
        run: |
          git push origin master
