name: Daily update
on:
  schedule:
    - cron: '20 6 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Ruby + Bundler cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update gem dependencies
        run: |
          nix-shell -p bundix --run ./tools/bundix_all.sh

          git add packages
          git diff --cached --quiet && exit 0

          git commit -m "packages: update gem dependencies"

      - name: Update webui dependencies
        run: |
          cd webui

          nix-shell --run "composer update"
          [ -d vendor ] && rm -rf vendor
          nix-shell --run "composer2nix --name vpsadmin-webui"

          git add composer.lock composer-env.nix php-packages.nix
          git diff --cached --quiet && exit 0

          git commit -m "webui: update dependencies"

      - name: Push updates
        run: |
          git push origin master

