name: Notification templates

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check notification templates
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.22.2

      - name: Check flake
        run: nix flake check --print-build-logs
